import { useMemo, useState } from 'react'
import { ArrowUpRight, Menu, X, Search, SlidersHorizontal, Sparkles, GitCompareArrows, CircleCheck, Clock3, Download, Mail } from 'lucide-react'
import './App.css'

const problems = [
  ['PS-041','AI & ML','Forecast crop disease outbreaks from weather and satellite signals','Ministry of Agriculture','Software','Hard',84],
  ['PS-087','Healthcare','Low-bandwidth maternal health triage for district clinics','Health Systems Lab','Software','Medium',62],
  ['PS-112','Smart Cities','Adaptive traffic signals for mixed-mode intersections','Urban Mobility Cell','Hardware','Hard',51],
  ['PS-136','Education','Offline-first language learning for government schools','Digital Learning Mission','Software','Easy',73],
  ['PS-159','Cybersecurity','Phishing simulation toolkit for first-time internet users','CERT Innovation Desk','Software','Medium',45],
  ['PS-174','Sustainability','Community-scale plastic sorting and traceability unit','Clean India Network','Hardware','Medium',38],
  ['PS-205','Financial Inclusion','Voice-led savings assistant for rural households','Inclusion Finance Forum','Software','Easy',69],
  ['PS-219','Disaster Management','Flood route intelligence for emergency responders','National Resilience Lab','Software','Hard',31],
]
const themes = ['Artificial Intelligence','Agriculture','Healthcare','Education','Sustainability','Smart Cities','Cybersecurity','Mobility','Financial Inclusion','Accessibility']
const timeline = [
  ['01','Problem statements','Published', '15 AUG'],['02','Institution registration','Open window','01 SEP'],['03','Team formation','Build your crew','15 SEP'],['04','Idea submission','Make it tangible','30 SEP'],['05','Screening','Expert review','12 OCT'],['06','Grand finale','Build what matters','20 NOV']
]

function App(){
 const [menu,setMenu]=useState(false); const [query,setQuery]=useState(''); const [type,setType]=useState('All'); const [selected,setSelected]=useState(null); const [compare,setCompare]=useState([]); const [faq,setFaq]=useState(0); const [role,setRole]=useState('Student');
 const filtered=useMemo(()=>problems.filter(p=>(type==='All'||p[4]===type)&&p.join(' ').toLowerCase().includes(query.toLowerCase())),[query,type])
 const toggleCompare=(p)=>setCompare(c=>c.some(x=>x[0]===p[0])?c.filter(x=>x[0]!==p[0]):c.length<3?[...c,p]:c)
 return <div className="app">
  <header className="header"><a className="brand" href="#top"><span className="brand-mark">SIH</span><span>SMART INDIA<br/><b>HACKATHON</b></span></a><nav>{[['About','#about'],['Challenges','#challenges'],['Timeline','#timeline'],['Editions','#editions'],['Resources','#resources']].map(([x,y])=><a href={y} key={x}>{x}</a>)}</nav><div className="header-actions"><a className="text-link" href="#participate">Participate <ArrowUpRight size={15}/></a><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></header>
  {menu&&<div className="mobile-menu">{[['About','#about'],['Challenges','#challenges'],['Find your challenge','#match'],['Timeline','#timeline'],['Editions','#editions'],['Resources','#resources'],['Participate','#participate']].map(([x,y])=><a onClick={()=>setMenu(false)} href={y} key={x}>{x}<ArrowUpRight size={18}/></a>)}</div>}
  <main id="top">
   <section className="hero"><div className="hero-grid"></div><div className="hero-copy"><p className="eyebrow"><span className="pulse"></span> EDITION 2025 / NOW OPEN</p><h1>Build what<br/><em>matters.</em></h1><p className="hero-desc">India's student innovation platform for turning real-world challenges into solutions with consequence.</p><div className="hero-actions"><a className="button button-primary" href="#challenges">Explore challenges <ArrowUpRight size={18}/></a><a className="button button-ghost" href="#match">Find your fit <Sparkles size={17}/></a></div></div><div className="hero-art"><div className="orbit orbit-a"></div><div className="orbit orbit-b"></div><div className="node n1">AI</div><div className="node n2">IN</div><div className="node n3">∞</div><div className="art-core">25<br/><small>YEARS OF<br/>MAKING</small></div><div className="hero-label label-a">01 / REAL PROBLEMS</div><div className="hero-label label-b">∞ / POSSIBILITY</div></div><div className="hero-foot"><span>SCROLL TO EXPLORE</span><span className="line"></span><span>28.6139° N / 77.2090° E</span></div></section>
   <section className="intro section" id="about"><div className="section-kicker">01 — THE PLATFORM</div><div className="intro-grid"><h2>Where ambition<br/><em>meets impact.</em></h2><div><p className="lede">Smart India Hackathon is a national stage for students who refuse to accept the way things are.</p><p className="body-copy">Every edition brings ministries, industry, and young builders into the same room — not to discuss the future, but to prototype it. From a district clinic to a satellite signal, the briefs are real. The opportunity is yours.</p><a className="arrow-link" href="#timeline">See how it works <ArrowUpRight size={17}/></a></div></div><div className="stat-strip">{[['24K+','students'],['1.8K','institutes'],['600+','challenges'],['14','editions']].map(([n,l])=><div className="stat" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
   <section className="challenge-intro section" id="challenges"><div className="section-kicker">02 — THE BRIEFS</div><div className="formula"><span>REAL<br/><em>PROBLEMS</em></span><b>+</b><span>STUDENT<br/><em>TEAMS</em></span><b>+</b><span>TECH<br/><em>THAT MOVES</em></span><b>=</b><span className="impact">IMPACT<span className="dot">.</span></span></div><div className="featured-row">{problems.slice(0,3).map(p=><article className="featured-card" key={p[0]} onClick={()=>setSelected(p)}><div className="card-top"><span className="mono">{p[0]}</span><span className="badge">{p[4]}</span></div><h3>{p[2]}</h3><div className="card-bottom"><span>{p[1]}</span><ArrowUpRight size={19}/></div></article>)}</div><a className="button button-dark" href="#explorer">Browse all challenges <ArrowUpRight size={17}/></a></section>
   <section className="explorer section" id="explorer"><div className="section-heading"><div><div className="section-kicker">03 — FIND YOUR BRIEF</div><h2>Choose a problem<br/><em>worth solving.</em></h2></div><p>Every challenge is a door. Find the one that opens onto your team's strongest work.</p></div><div className="filter-bar"><div className="search-box"><Search size={18}/><input id="search" aria-label="Search problem statements" placeholder="Search by challenge, theme or ministry" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-pills">{['All','Software','Hardware'].map(x=><button className={type===x?'active':''} key={x} onClick={()=>setType(x)}>{x}</button>)}</div><button className="filter-icon" aria-label="More filters"><SlidersHorizontal size={18}/></button></div><div className="result-line"><span>{filtered.length} of {problems.length} challenges</span><span className="mono">SORTED BY RELEVANCE</span></div><div className="problem-list">{filtered.map(p=><article className="problem-row" key={p[0]}><div className="problem-number mono">{p[0]}</div><div className="problem-main"><span className="meta">{p[1]} · {p[3]}</span><h3>{p[2]}</h3><div className="tags"><span>{p[4]}</span><span>{p[5]}</span><span>{p[6]} ideas</span></div></div><button className="compare-btn" onClick={()=>toggleCompare(p)} aria-label={`Compare ${p[0]}`}>{compare.some(x=>x[0]===p[0])?<CircleCheck size={19}/>:<GitCompareArrows size={19}/>}</button><button className="row-arrow" onClick={()=>setSelected(p)} aria-label={`Open ${p[0]}`}><ArrowUpRight size={20}/></button></article>)}</div></section>
   <section className="match section" id="match"><div className="match-panel"><div><div className="section-kicker">04 — ORIGINAL FEATURE</div><h2>Find your<br/><em>challenge.</em></h2><p>Tell us what your team cares about. We’ll point you toward a brief with a pulse.</p></div><div className="match-options"><p className="label">I want to build for</p><div className="option-grid">{themes.slice(0,6).map(t=><button key={t} onClick={()=>{}}>{t}</button>)}</div><a className="button button-primary" href="#explorer">Show my matches <Sparkles size={17}/></a></div></div></section>
   <section className="journey section"><div className="section-heading"><div><div className="section-kicker">05 — THE JOURNEY</div><h2>From brief<br/><em>to breakthrough.</em></h2></div><div className="journey-id"><span>DEMO TEAM ID</span><b>IN—25—0417</b></div></div><div className="journey-track">{['Submitted','Shortlisted','Nominated','Finalist'].map((x,i)=><div className={`journey-step ${i<2?'done':''}`} key={x}><div className="step-dot">{i<2?'✓':String(i+1).padStart(2,'0')}</div><h3>{x}</h3><span>{i<2?'12 SEP 2025':i===2?'UP NEXT':'20 NOV 2025'}</span></div>)}</div><div className="progress-note"><Clock3 size={17}/><span>Demo state · Your team is currently shortlisted</span></div></section>
   <section className="timeline section" id="timeline"><div className="section-kicker">06 — MARK THE MOMENT</div><div className="timeline-head"><h2>The road to<br/><em>the finale.</em></h2><span className="mono">2025 / 06 MILESTONES</span></div><div className="timeline-scroll">{timeline.map(([n,t,d,date])=><div className="time-card" key={n}><span className="time-number mono">{n}</span><div className="time-index"></div><span className="time-date">{date}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
   <section className="themes section"><div className="section-kicker">07 — THE TERRITORY</div><h2>Many frontiers.<br/><em>One instinct.</em></h2><div className="theme-list">{themes.map((t,i)=><a href="#explorer" className="theme-item" key={t}><span className="mono">0{i+1}</span><b>{t}</b><ArrowUpRight size={19}/></a>)}</div></section>
   <section className="editions section" id="editions"><div className="section-kicker">08 — THE ARCHIVE</div><div className="edition-feature"><div><span className="mono">EDITION / 2023</span><h2>Ideas that<br/><em>left a mark.</em></h2><p>From climate intelligence to assistive technology, the archive is a record of students who chose to build beyond the obvious.</p><a className="arrow-link" href="#resources">Explore the archive <ArrowUpRight size={17}/></a></div><div className="edition-number">14</div></div></section>
   <section className="participate section" id="participate"><div className="section-kicker">09 — YOUR ENTRY POINT</div><div className="participate-head"><h2>Where do you<br/><em>begin?</em></h2><p>This is a concept experience. Select a role to see how your first step could look.</p></div><div className="role-tabs">{['Student','SPOC','Problem creator'].map(x=><button className={role===x?'active':''} onClick={()=>setRole(x)} key={x}>{x}</button>)}</div><div className="role-panel"><div><span className="mono">YOU ARE A {role.toUpperCase()}</span><h3>{role==='Student'?'Bring your curiosity.':role==='SPOC'?'Move your institution forward.':'Put a real brief on the table.'}</h3><p>{role==='Student'?'Explore challenges, gather your team, and build something that earns its place in the world.':'A mocked entry point for this student redesign concept.'}</p></div><a className="button button-primary" href="#footer">Continue as {role} <ArrowUpRight size={17}/></a></div></section>
   <section className="resources section" id="resources"><div className="section-kicker">10 — KEEP GOING</div><div className="resource-grid"><div><h2>Make room<br/><em>for better.</em></h2><p className="body-copy">Guides, timelines, and the small details that help big ideas arrive ready.</p></div><div className="resource-links">{['Student handbook','Evaluation criteria','Team formation guide','Hardware edition guide'].map((x,i)=><a href="#footer" key={x}><span><span className="mono">0{i+1}</span>{x}</span><Download size={17}/></a>)}</div></div></section>
  </main>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><span className="mono">{selected[0]} · {selected[4]} · {selected[5]}</span><h2>{selected[2]}</h2><p className="meta">{selected[3]} · {selected[1]}</p><p className="modal-copy">Design a resilient, human-centred solution for this challenge. This illustrative brief invites teams to combine field research, thoughtful systems, and responsible technology.</p><div className="modal-stats"><span><b>{selected[6]}</b> ideas submitted</span><span><b>{selected[4]}</b> edition</span></div><button className="button button-primary" onClick={()=>toggleCompare(selected)}> {compare.some(x=>x[0]===selected[0])?'Remove from compare':'Add to compare'} <GitCompareArrows size={17}/></button></article></div>}
  {compare.length>0&&<div className="compare-dock"><span><b>{compare.length}</b> selected for comparison</span><button onClick={()=>setCompare([])}>Clear</button><a href="#explorer">Review <ArrowUpRight size={16}/></a></div>}
  <footer id="footer"><div className="footer-top"><div className="brand footer-brand"><span className="brand-mark">SIH</span><span>SMART INDIA<br/><b>HACKATHON</b></span></div><h2>Build what<br/><em>matters.</em></h2></div><div className="footer-links"><div><span>EXPLORE</span><a href="#about">About SIH</a><a href="#challenges">Challenges</a><a href="#timeline">Timeline</a></div><div><span>PARTICIPATE</span><a href="#match">Find your challenge</a><a href="#participate">Role entry</a><a href="#editions">Editions</a></div><div><span>CONNECT</span><a href="mailto:concept@sih.example"><Mail size={15}/> Email</a><a href="#footer">in&nbsp; LinkedIn</a><a href="#footer">◎&nbsp; Instagram</a></div></div><div className="footer-bottom"><p>Smart India Hackathon is an initiative of the Ministry of Education's Innovation Cell (MIC) & AICTE.</p><p>This website is a student redesign concept created for educational/hackathon purposes. It is not an official Smart India Hackathon platform.</p><span>© 2025 SIH CONCEPT / MADE TO MOVE</span></div></footer>
 </div>
}
export default App
